---
title: 'EDS 230/ESM232: Assignment 2'
author: "Roshni Katrak-Adefowora, Scout Leonard, Nikole Vannest"
date: '`r format(Sys.time(), "%m/%d/%Y")`'
output: 
  pdf_document:
    toc: false
    number_sections: yes
header-includes:
  - \setlength{\parindent}{1em}
  - \usepackage{float}
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
packages=c("here",
           "readr",
           "tidyverse")

for (i in packages) {
  if (require(i,character.only=TRUE)==FALSE) {
    install.packages(i,repos='http://cran.us.r-project.org')
  }
  else {
    require(i,character.only=TRUE)
  }
}

source(here("R", "almond_yield.R"))
```
 
# Read in Climate Data

```{r}
climate_data <- read_delim(here("data", "clim.txt")) %>% 
  rename(date = day,
         day = month,
         month = year,
         year = wy)
```

# Subset Climate Data

```{r}
#filter climate dataset for february minimum temperature
feb_min_temps <- climate_data %>%
  filter(month == 2) %>% 
  group_by(year) %>% 
  summarise(feb_min_temp_c = min(tmin_c))

#filter climate dataset for february precipitation 
jan_precip <- climate_data %>% 
  filter(month == 1) %>%
  group_by(year) %>% 
  summarise(total_jan_precip_mm = sum(precip))
```

# Summarize Results

```{r}
years_list <- jan_precip$year
anomaly <- c()

for (i in 1:length(years_list)){
  
  anomaly[i] <- almond_yield(precip = jan_precip$total_jan_precip_mm[i], temp = feb_min_temps$feb_min_temp_c[i])
  
}
```

# Summary of Findings 

