---
title: "EDS 230/ESM232: Assignment 3"
author: "Roshni Katrak-Adefowora, Scout Leonard, Nikole Vannest"
date: '2022-04-14'
output: html_document
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
packages=c("here",
           "readr",
           "tidyverse")

for (i in packages) {
  if (require(i,character.only=TRUE)==FALSE) {
    install.packages(i,repos='http://cran.us.r-project.org')
  }
  else {
    require(i,character.only=TRUE)
  }
}

source(here("R", "almond_yield.R"))
```
 
# Read in Climate Data

```{r}
climate_data <- read.table(here("data", "clim.txt"))
options(scipen = 999)
```

# Subset Climate Data

```{r}
#filter climate dataset for february minimum temperature
feb_min_temps <- climate_data %>%
  filter(month == 2) %>% 
  group_by(wy) %>% 
  summarise(feb_min_temp_c = mean(tmin_c))

#filter climate dataset for february precipitation 
jan_precip <- climate_data %>% 
  filter(month == 1) %>%
  group_by(wy) %>% 
  summarise(total_jan_precip_mm = sum(precip))
```

# Summarize Results

```{r}
years_list <- jan_precip$wy
anomaly <- c()

for (i in 1:length(years_list)){
  
  anomaly[i] <- almond_yield(precip = jan_precip$total_jan_precip_mm[i], temp = feb_min_temps$feb_min_temp_c[i])
  
}

anomaly_df <- as.data.frame(cbind(years_list, 
                                  anomaly,
                                  jan_precip$total_jan_precip_mm,
                                  feb_min_temps$feb_min_temp_c))

```

# Almond Profit Model

[Basis for the 1.05 tons/acre average annual yield value.](https://apps1.cdfa.ca.gov/FertilizerResearch/docs/Almond_Production_CA.pdf)

```{r profit}
source(here("R", "profit.R"))

# Historical prices of almonds (lbs)
prices <- read.table(here("data", "hist_price.txt"), 
                     header = T) 

# Convert lbs to tons
prices$value_tons <- prices$Value_lbs * 2000

#add column with average yield
prices <- prices %>% 
  mutate(average_yield = 1.05)

# run model with average price
# (Anomaly isn't actual yield bc it has negative values, how do we want to spin this?)

money <- profit(anomaly = anomaly, 
                price = mean(prices$value_tons),
                average_yield = prices$average_yield)

# create sensitivity analysis with range of prices from prices data frame?


```


```{r plot data}
# preliminary plot

money_df <- as.data.frame(cbind(years_list, 
                                money,
                                anomaly))

money_df %>% ggplot(aes(x = years_list)) +
  geom_point(aes(y = money)) +
  geom_line(aes(y = money)) 
```

Sources: US Department of Agriculture: USDA Farm Price Received
