---
title: "EDS 230/ESM232: Assignment 3"
author: "Roshni Katrak-Adefowora, Scout Leonard, Nikole Vannest"
date: '2022-04-14'
output:
  html_document:
    toc: true
    toc_float: yes
    smooth_scroll: true
    theme: journal
    highlight: textmate
    code_folding: show
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
packages=c("here",
           "readr",
           "tidyverse",
           "ggpubr",
           "ggpubr",
           "knitr")

for (i in packages) {
  if (require(i,character.only=TRUE)==FALSE) {
    install.packages(i,repos='http://cran.us.r-project.org')
  }
  else {
    require(i,character.only=TRUE)
  }
}

source(here("R", "almond_anomaly.R"))
source(here("R", "profit.R"))
```

# Prep for Sensitivity Analysis (code from assignment 2)

## Read in Climate Data

```{r}
climate_data <- read.table(here("data", "clim.txt"))
options(scipen = 999)
```

## Subset Climate Data

```{r}
#filter climate dataset for february minimum temperature
feb_min_temps <- climate_data %>%
  filter(month == 2) %>% 
  group_by(wy) %>% 
  summarise(feb_min_temp_c = mean(tmin_c))

#filter climate dataset for february precipitation 
jan_precip <- climate_data %>% 
  filter(month == 1) %>%
  group_by(wy) %>% 
  summarise(total_jan_precip_mm = sum(precip))
```

## Summarize Results

```{r}
years_list <- jan_precip$wy
anomaly <- c()

for (i in 1:length(years_list)){
  
  anomaly[i] <- almond_anomaly(precip = jan_precip$total_jan_precip_mm[i], temp = feb_min_temps$feb_min_temp_c[i])
  
}

anomaly_df <- as.data.frame(cbind(years_list, 
                                  anomaly,
                                  jan_precip$total_jan_precip_mm,
                                  feb_min_temps$feb_min_temp_c))

```

# Run Sensitivity Analysis

```{r secondsensitivity}
# generate samples for both parameters
nsamples = 22

# price in dollars per ton
deviation = 0.15
price_base_thresh = 4000

price = runif(min = price_base_thresh - deviation * price_base_thresh,
              max = price_base_thresh + deviation * price_base_thresh,
              n = nsamples)

#average yield
average_yield = rnorm(mean = 1.5, 
              sd = 0.1, 
              n = nsamples)

# make df of params
parms = cbind.data.frame(price, average_yield)

# use pmap 
# takes function name and then names of all parameters that don't change
results = parms %>% 
  pmap(profit,
       anomaly = data.frame(anomaly_df$anomaly))

#make a list of mean profits for each price x yield scenario
results_means <- lapply(as.data.frame(results), 
                        mean) 

# make a dataframe of each combination of params with their average profit outcome
results_df <- cbind(price, average_yield, 
                    results_means) %>% 
  as.data.frame()
```

The resulting dataframe, `results_df`, has 22 observations for 22 different price and average yield scenarios, and then the resulting profit outcome, in $ per acre. 

```{r test results_df}
head(results_df, 5) %>% 
  kable()
```



```{r}
#plot results
plot_1 = ggplot(results_df, aes(x = as.numeric(price), 
                                y = as.numeric(results_means))) +
                  geom_point(color = as.numeric(results_means)) +
  labs(x = "Price of Almonds in Dollars per Ton",
       y = "Profit in Dollars per Acre") +
  theme_minimal()

plot_2 = ggplot(results_df, aes(x = as.numeric(average_yield), 
                                y = as.numeric(results_means))) +
                  geom_point(color = as.numeric(results_means)) +
  labs(x = "Yield of Almonds in Tons per Acre",
       y = "Profit in Dollars per Acre") +
  theme_minimal()

profit_plots <- ggarrange(plot_1, plot_2) 

profit_plots <- annotate_figure(profit_plots,
                top = text_grob("Sensitivity Analysis of Almond Profit to Average Yield and Almond Price", face = "bold", size = 14))

profit_plots
```

```{r}
ggsave("profit_plots.png",
       plot = profit_plots,
       path = here("viz"))
```

